(val x 3)
(define addone (x) (+ x 1))
(print_endline (string_of_int (addone 5)))
(print_endline (string_of_int ((lambda (x) (+ x 1)) 3)))
(print_endline (string_of_bool (or #t #f)))
(List.length '(1 2 3))
(List.map (+ 1) '(1 2 3))
